### PR TITLE
Add Automattic

### PR DESCRIPTION
**Pull request by nb**
Thank you so much for the cool service :-) Let me know if all looks good.

### CODE REVIEW

**Comment by 4kimov** [comment]
Thank you so much for submitting via the wizard (an easier website interface coming soon). Right now the website supports only up to 3 projects/products so I had to cut the last 2, but other than that, looks good! https://fossfox.com/automattic (the homepage will link to this automatically later today)

**Comment by nb** [comment]
Thanks for the quick merge, @4kimov! Quick follow-up question – on the webpage I see the role is now “[Blockchain](https://fossfox.com/blockchain-jobs), [Security](https://fossfox.com/security-jobs)”, which doesn't really match the expectations from the job. Not sure how is this field controlled.

**Comment by 4kimov** [comment]
@nb Thank you for catching that. Sorry, looks like an error in our internal mapping. Should be fixed now. I see "Devops, Security" type, which should be more appropriate.

**Comment by nb** [comment]
Thanks again! Devops/security sounds good.

**Pull request merged**
